# Travis CI configuration file for psycopg2

dist: trusty
sudo: required

env:
  - PGVER=9.6
  - PGVER=9.5

install:
  - source regress/travis_prepare.sh
  - make
  - sudo make install

script:
  - regress/travis_test.sh

notifications:
  email: false
